/**
 * Indicates a group identification generated by clustering algorithms.
 * 
 * @author chirantannath
 */
public record ClusterLabel<R extends Row>(int label, R representative) {
  /** Creates a cluster label with no assigned representative. */
  public static <R extends Row> ClusterLabel<R> noRepresentative(int label) {
    return new ClusterLabel<>(label, null);
  }

  /** An empty cluster label (when failed to group in any group). */
  public static final ClusterLabel<? extends Row> EMPTY = noRepresentative(-1);

  /** Creates an empty cluster label (when failed to group in any group). */
  @SuppressWarnings("unchecked")
  public static <R extends Row> ClusterLabel<R> empty() {
    return (ClusterLabel<R>) EMPTY;
  }

  public final boolean hasRepresentative() {
    return representative != null;
  }

  public final boolean isEmpty() {
    return label < 0;
  }
}
